create table products (
	product_id VARCHAR(2),
	product_barcode VARCHAR(12),
	product_name VARCHAR(10),
	product_description VARCHAR(1),
	product_inv_stock VARCHAR(2),
	product_inv_in_transit VARCHAR(1),
	product_inv_total VARCHAR(2),
	product_min_qty VARCHAR(1),
	product_purchase_qty VARCHAR(1),
	product_location_id VARCHAR(1),
	product_category_id VARCHAR(1),
	product_supplier_id VARCHAR(1)
);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (18, 182483099615, 'Broccoli', null, 50, 0, 50, null, null, null, 4, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (12, 495939702557, 'Beef', 'Grass-fed organic beef', 50, 0, 50, null, null, null, 3, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (2, 212537433256, 'Egg', 'Fresh grass-fed chicken eggs', 50, 0, 50, null, null, null, 1, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (2, 212537433256, 'Egg', 'Fresh grass-fed chicken eggs', 50, 0, 50, null, null, null, 1, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (23, 665540775330, 'Tomato', null, 50, 0, 50, null, null, null, 4, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (7, 161350340690, 'Orange', 'Florida oranges', 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (4, 746231132065, 'Apple', 'Fresh red apples from local orchard', 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (17, 734157209540, 'Venison', null, 50, 0, 50, null, null, null, 3, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (15, 184413301378, 'Pork', null, 50, 0, 50, null, null, null, 3, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (4, 746231132065, 'Apple', 'Fresh red apples from local orchard', 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (19, 678699111607, 'Corn', null, 50, 0, 50, null, null, null, 4, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (8, 543702056870, 'Pear', null, 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (3, 389805537188, 'Milk', 'Raw milk from grass-fed cows', 50, 0, 50, null, null, null, 1, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (17, 734157209540, 'Venison', null, 50, 0, 50, null, null, null, 3, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (23, 665540775330, 'Tomato', null, 50, 0, 50, null, null, null, 4, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (23, 665540775330, 'Tomato', null, 50, 0, 50, null, null, null, 4, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (13, 991870651326, 'Chicken', null, 50, 0, 50, null, null, null, 3, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (10, 388960092537, 'Plum', null, 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (9, 265818394731, 'Pineapple', null, 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (2, 212537433256, 'Egg', 'Fresh grass-fed chicken eggs', 50, 0, 50, null, null, null, 1, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (2, 212537433256, 'Egg', 'Fresh grass-fed chicken eggs', 50, 0, 50, null, null, null, 1, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (19, 678699111607, 'Corn', null, 50, 0, 50, null, null, null, 4, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (10, 388960092537, 'Plum', null, 50, 0, 50, null, null, null, 2, null);
insert into products (product_id, product_barcode, product_name, product_description, product_inv_stock, product_inv_in_transit, product_inv_total, product_min_qty, product_purchase_qty, product_location_id, product_category_id, product_supplier_id) values (7, 161350340690, 'Orange', 'Florida oranges', 50, 0, 50, null, null, null, 2, null);
